name: Daily

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true

    - uses: actions-rs/cargo@v1
      name: Build
      with:
        command: build
        args: --all-features
    
    - uses: actions-rs/cargo@v1
      name: Test
      with:
        command: test
        args: --all-features
