name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish_crates:
    name: Release
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish
        env:
          TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo login $TOKEN
          cargo publish --allow-dirty
