name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      name: Install Rust 
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy 

    - uses: actions-rs/cargo@v1
      name: Linter 
      with:
        command: fmt
        args: --all -- --check
    
    - uses: actions-rs/cargo@v1
      name: Build
      with:
        command: build
    
    - uses: actions-rs/cargo@v1
      name: Test
      with:
        command: test
        args: --verbose
    
    - uses: actions-rs/cargo@v1
      name: Build (all features)
      with:
        command: build
        args: --all-features

    - uses: actions-rs/cargo@v1
      name: Test (all features)
      with:
        command: test
        args: --verbose --all-features
